version: "3"
services:
  frontend:
    image: gyungku/topster-front
    env_file:
      - .env

  nginx:
    restart: always
    image: gyungku/topster-nginx
    ports:
      - "80:80"

  backend:
    image: gyungku/topster-backend
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul